#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

rm -rf .agents/skills
mkdir -p .agents/skills docs

# Curated design catalogue (project scope). This installs the catalogue's project skills.
npx -y skills add podo/design-agent-skills -y

# Explicit sources discussed for CS DUO. Later installs intentionally win name collisions.
npx -y skills add anthropics/claude-code --skill frontend-design -y
npx -y skills add nmhjklnm/frontend-skills -y
npx -y skills add rikre/design-skills -y
npx -y skills add richtabor/agent-skills --skill motion-design -y
npx -y skills add TerminalSkills/skills --skill design-md -y

# The Microsoft frontend-design-review skill was explicitly excluded.
for skill_file in .agents/skills/*/SKILL.md; do
  [[ -f "$skill_file" ]] || continue
  if grep -Eq '^name:[[:space:]]*frontend-design-review[[:space:]]*$' "$skill_file"; then
    rm -rf "$(dirname "$skill_file")"
  fi
done

if find .agents/skills -mindepth 2 -maxdepth 2 -name SKILL.md -print0 | xargs -0 grep -lE '^name:[[:space:]]*frontend-design-review[[:space:]]*$' | grep -q .; then
  echo "frontend-design-review is still installed" >&2
  exit 1
fi

skill_count="$(find .agents/skills -mindepth 2 -maxdepth 2 -name SKILL.md | wc -l | tr -d ' ')"

cat > docs/DESIGN_SKILLS.md <<EOF
# Design agent skills

Project-scoped design skills live in \`.agents/skills/\` and are generated by \`scripts/install-design-skills.sh\`.

Installed sources:

- \`podo/design-agent-skills\` — design skill catalogue
- \`anthropics/claude-code\` — \`frontend-design\`
- \`nmhjklnm/frontend-skills\` — frontend/UI skill collection including \`calm-ui\`
- \`rikre/design-skills\` — visual style/design skill collection
- \`richtabor/agent-skills\` — \`motion-design\`
- \`TerminalSkills/skills\` — \`design-md\`

Explicitly excluded:

- Microsoft \`frontend-design-review\`

The install currently resolves to **${skill_count} project skills**. Re-run the installer when intentionally updating upstream skills, then review and commit the resulting diff.
EOF

echo "Installed ${skill_count} project design skills."
